// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.34209
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Coder.EndToEndTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Verify using the Other Specify for drop-downs and search-lists is supported and t" +
        "he around trip integration works successfully.")]
    public partial class VerifyUsingTheOtherSpecifyForDrop_DownsAndSearch_ListsIsSupportedAndTheAroundTripIntegrationWorksSuccessfully_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "specETE_SpecifyTermsDropdown.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Verify using the Other Specify for drop-downs and search-lists is supported and t" +
                    "he around trip integration works successfully.", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
            "via the Other Specify dropdown option on the supplemental field")]
        [NUnit.Framework.CategoryAttribute("DFT")]
        [NUnit.Framework.CategoryAttribute("PBMCC40159_001b")]
        [NUnit.Framework.CategoryAttribute("ReleaseRave2013.2.0")]
        [NUnit.Framework.CategoryAttribute("DTMCC68955")]
        public virtual void ACodingDecisionWillBeAcceptedByEDCForAVerbatimThatHasDataSubmittedViaTheOtherSpecifyDropdownOptionOnTheSupplementalField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
                    "via the Other Specify dropdown option on the supplemental field", new string[] {
                        "DFT",
                        "PBMCC40159_001b",
                        "ReleaseRave2013.2.0",
                        "DTMCC68955"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("a Rave project registration with dictionary \"WhoDrugDDEB2 ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("Rave Modules App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Field",
                        "Dictionary",
                        "Locale",
                        "CodingLevel",
                        "Priority",
                        "IsApprovalRequired",
                        "IsAutoApproval",
                        "SupplementalTerms"});
            table1.AddRow(new string[] {
                        "ETE17",
                        "CoderField17",
                        "<Dictionary>",
                        "<Locale>",
                        "PRODUCTSYNONYM",
                        "1",
                        "true",
                        "true",
                        ""});
#line 10
  testRunner.And("a Rave Coder setup with the following options", ((string)(null)), table1, "And ");
#line 13
 testRunner.When("a Rave Draft is published and pushed using draft \"<Draft>\" for Project \"<SourceSy" +
                    "stemStudyName>\" to environment \"Production\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.And("adding a new subject \"TST\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "ControlType"});
            table2.AddRow(new string[] {
                        "Medical Term",
                        "child advil cold extreme",
                        "LongText"});
            table2.AddRow(new string[] {
                        "Specify Dropdown",
                        "Other Option",
                        "DropDownList"});
            table2.AddRow(new string[] {
                        "Specify Dropdown",
                        "terrible head pain",
                        ""});
#line 15
 testRunner.And("adding a new verbatim term to form \"ETE17\"", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value",
                        "Column",
                        "Table"});
            table3.AddRow(new string[] {
                        "ETE17.Specify Dropdown",
                        "Supplemental Term",
                        "Supplements Table"});
            table3.AddRow(new string[] {
                        "terrible head pain",
                        "Supplemental Value",
                        "Supplements Table"});
#line 20
    testRunner.Then("Coder Source Terms contains the following", ((string)(null)), table3, "Then ");
#line 24
 testRunner.When("task \"child advil cold extreme\" is coded to term \"CHILDRENS ADVIL COLD\" at search" +
                    " level \"Preferred Name\" with code \"010502 01 015 9\" at level \"PN\" and a synonym " +
                    "is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.Then("Rave Adverse Events form \"ETE17\" should display \"CHILDRENS ADVIL COLD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 26
 testRunner.And("Coder tasks should display \"CHILDRENS ADVIL COLD\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
            "via the Other Specify dropdown option")]
        [NUnit.Framework.CategoryAttribute("DFT")]
        [NUnit.Framework.CategoryAttribute("PBMCC40159_001d")]
        [NUnit.Framework.CategoryAttribute("ReleaseRave2013.2.0")]
        [NUnit.Framework.CategoryAttribute("DTMCC68955")]
        public virtual void ACodingDecisionWillBeAcceptedByEDCForAVerbatimThatHasDataSubmittedViaTheOtherSpecifyDropdownOption()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
                    "via the Other Specify dropdown option", new string[] {
                        "DFT",
                        "PBMCC40159_001d",
                        "ReleaseRave2013.2.0",
                        "DTMCC68955"});
#line 32
this.ScenarioSetup(scenarioInfo);
#line 33
 testRunner.Given("a Rave project registration with dictionary \"MedDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 34
 testRunner.And("Rave Modules App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Field",
                        "Dictionary",
                        "Locale",
                        "CodingLevel",
                        "Priority",
                        "IsApprovalRequired",
                        "IsAutoApproval",
                        "SupplementalTerms"});
            table4.AddRow(new string[] {
                        "ETE17",
                        "CoderField17",
                        "<Dictionary>",
                        "<Locale>",
                        "LLT",
                        "1",
                        "true",
                        "true",
                        ""});
#line 35
  testRunner.And("a Rave Coder setup with the following options", ((string)(null)), table4, "And ");
#line 38
 testRunner.When("a Rave Draft is published and pushed using draft \"<Draft>\" for Project \"<SourceSy" +
                    "stemStudyName>\" to environment \"Production\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.And("adding a new subject \"TST\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "ControlType"});
            table5.AddRow(new string[] {
                        "Specify Dropdown",
                        "Other Option",
                        "DropDownList"});
            table5.AddRow(new string[] {
                        "Specify Dropdown",
                        "terrible head pain",
                        ""});
#line 40
 testRunner.And("adding a new verbatim term to form \"ETE17\"", ((string)(null)), table5, "And ");
#line 44
 testRunner.When("task \"terrible head pain\" is coded to term \"headache\" at search level \"Lower Leve" +
                    "l Term\" with code \"10019211\" at level \"LLT\" and a synonym is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("Rave Adverse Events form \"ETE17\" should display \"headache\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
 testRunner.And("Coder tasks should display \"headache\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
