// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Coder.EndToEndTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Verify using the Other Specify for drop-downs and search-lists is supported and t" +
        "he around trip integration works successfully.")]
    [NUnit.Framework.CategoryAttribute("specETE_SpecifyTermsDropdown")]
    [NUnit.Framework.CategoryAttribute("EndToEndDynamicSegment")]
    public partial class VerifyUsingTheOtherSpecifyForDrop_DownsAndSearch_ListsIsSupportedAndTheAroundTripIntegrationWorksSuccessfully_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "specETE_SpecifyTermsDropdown.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Verify using the Other Specify for drop-downs and search-lists is supported and t" +
                    "he around trip integration works successfully.", "", ProgrammingLanguage.CSharp, new string[] {
                        "specETE_SpecifyTermsDropdown",
                        "EndToEndDynamicSegment"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
            "via the Other Specify dropdown option on the supplemental field")]
        [NUnit.Framework.CategoryAttribute("DFT")]
        [NUnit.Framework.CategoryAttribute("PBMCC40159_001b")]
        [NUnit.Framework.CategoryAttribute("ReleaseRave2013.2.0")]
        [NUnit.Framework.CategoryAttribute("DTMCC68955")]
        public virtual void ACodingDecisionWillBeAcceptedByEDCForAVerbatimThatHasDataSubmittedViaTheOtherSpecifyDropdownOptionOnTheSupplementalField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
                    "via the Other Specify dropdown option on the supplemental field", new string[] {
                        "DFT",
                        "PBMCC40159_001b",
                        "ReleaseRave2013.2.0",
                        "DTMCC68955"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("a Rave project registration with dictionary \"WhoDrug-DDE-B2 ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.And("Rave Modules App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Field",
                        "Dictionary",
                        "Locale",
                        "CodingLevel",
                        "Priority",
                        "IsApprovalRequired",
                        "IsAutoApproval",
                        "SupplementalTerms"});
            table1.AddRow(new string[] {
                        "ETE17",
                        "Coding Field",
                        "<Dictionary>",
                        "",
                        "PRODUCTSYNONYM",
                        "1",
                        "true",
                        "true",
                        "ETEMCC40159DROPDOWN"});
#line 15
  testRunner.And("a Rave Coder setup with the following options", ((string)(null)), table1, "And ");
#line 18
 testRunner.When("a Rave Draft is published and pushed using draft \"<DraftName>\" for Project \"<Stud" +
                    "yName>\" to environment \"Prod\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.And("adding a new subject \"TST\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "ControlType"});
            table2.AddRow(new string[] {
                        "Coding Field",
                        "child advil cold extreme",
                        ""});
            table2.AddRow(new string[] {
                        "Log Dropdown Supplemental Field A",
                        "Other Option",
                        "DropDownList"});
            table2.AddRow(new string[] {
                        "Log Dropdown Supplemental Field A",
                        "terrible head pain",
                        ""});
#line 20
 testRunner.And("adding a new verbatim term to form \"ETE17\"", ((string)(null)), table2, "And ");
#line 25
 testRunner.And("Coder App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Term",
                        "Value"});
            table3.AddRow(new string[] {
                        "ETEMCC40159.ETEMCC40159DROPDOWN",
                        "terrible head pain"});
#line 26
 testRunner.Then("the \"child advil cold extreme\" task has the following supplemental information", ((string)(null)), table3, "Then ");
#line 29
 testRunner.When("task \"child advil cold extreme\" is coded to term \"CHILDRENS ADVIL COLD\" at search" +
                    " level \"Trade Name\" with code \"010502 01 015\" at level \"TN\" and a synonym is cre" +
                    "ated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.And("Rave Modules App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Level",
                        "Code",
                        "Term Path"});
            table4.AddRow(new string[] {
                        "ATC",
                        "M",
                        "MUSCULO-SKELETAL SYSTEM"});
            table4.AddRow(new string[] {
                        "ATC",
                        "M01",
                        "ANTIINFLAMMATORY AND ANTIRHEUMATIC PRODUCTS"});
            table4.AddRow(new string[] {
                        "ATC",
                        "M01A",
                        "ANTIINFLAMMATORY/ANTIRHEUMATIC PROD.,NON-STEROIDS"});
            table4.AddRow(new string[] {
                        "ATC",
                        "M01AE",
                        "PROPIONIC ACID DERIVATIVES"});
            table4.AddRow(new string[] {
                        "PRODUCT",
                        "010502 01 001",
                        "CO-ADVIL"});
            table4.AddRow(new string[] {
                        "PRODUCTSYNONYM",
                        "010502 01 015",
                        "CHILDRENS ADVIL COLD"});
#line 31
    testRunner.Then("the coding decision for verbatim \"child advil cold extreme\" on form \"ETE17\" for f" +
                    "ield \"Coding Field\" contains the following data", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
            "via the Other Specify dropdown option")]
        [NUnit.Framework.CategoryAttribute("DFT")]
        [NUnit.Framework.CategoryAttribute("PBMCC40159_001d")]
        [NUnit.Framework.CategoryAttribute("ReleaseRave2013.2.0")]
        [NUnit.Framework.CategoryAttribute("DTMCC68955")]
        public virtual void ACodingDecisionWillBeAcceptedByEDCForAVerbatimThatHasDataSubmittedViaTheOtherSpecifyDropdownOption()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("A coding decision will be accepted by EDC for a verbatim that has data submitted " +
                    "via the Other Specify dropdown option", new string[] {
                        "DFT",
                        "PBMCC40159_001d",
                        "ReleaseRave2013.2.0",
                        "DTMCC68955"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("a Rave project registration with dictionary \"MedDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
 testRunner.And("Rave Modules App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Form",
                        "Field",
                        "Dictionary",
                        "Locale",
                        "CodingLevel",
                        "Priority",
                        "IsApprovalRequired",
                        "IsAutoApproval"});
            table5.AddRow(new string[] {
                        "ETE17",
                        "Specify Dropdown",
                        "<Dictionary>",
                        "<Locale>",
                        "LLT",
                        "1",
                        "true",
                        "true"});
#line 48
  testRunner.And("a Rave Coder setup with the following options", ((string)(null)), table5, "And ");
#line 51
 testRunner.When("a Rave Draft is published and pushed using draft \"<DraftName>\" for Project \"<Stud" +
                    "yName>\" to environment \"Prod\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.And("adding a new subject \"TST\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field",
                        "Value",
                        "ControlType"});
            table6.AddRow(new string[] {
                        "Log Dropdown Supplemental Field A",
                        "Other Option",
                        "DropDownList"});
            table6.AddRow(new string[] {
                        "Log Dropdown Supplemental Field A",
                        "terrible head pain",
                        ""});
#line 53
 testRunner.And("adding a new verbatim term to form \"ETE17\"", ((string)(null)), table6, "And ");
#line 57
 testRunner.And("Coder App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("task \"terrible head pain\" is coded to term \"Head pain\" at search level \"Low Level" +
                    " Term\" with code \"10019198\" at level \"LLT\" and a synonym is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
    testRunner.And("Rave Modules App Segment is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Level",
                        "Code",
                        "Term Path"});
            table7.AddRow(new string[] {
                        "SOC",
                        "10029205",
                        "Nervous system disorders"});
            table7.AddRow(new string[] {
                        "HLGT",
                        "10019231",
                        "Headaches"});
            table7.AddRow(new string[] {
                        "HLT",
                        "10019233",
                        "Headaches NEC"});
            table7.AddRow(new string[] {
                        "PT",
                        "10019211",
                        "Headache"});
            table7.AddRow(new string[] {
                        "LLT",
                        "10019198",
                        "Head pain"});
#line 60
 testRunner.Then("the coding decision for verbatim \"terrible head pain\" on form \"ETE17\" for field \"" +
                    "Log Dropdown Supplemental Field A\" contains the following data", ((string)(null)), table7, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
