IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrackableObjects'
		 AND COLUMN_NAME = 'SourceUpdatedAt')
	ALTER TABLE TrackableObjects
	ADD SourceUpdatedAt DATETIME NOT NULL CONSTRAINT DF_TrackableObjects_SourceUpdatedAt DEFAULT ('1980-01-01 00:00:00.001')

GO
