IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'WorkflowRoles'
		 AND COLUMN_NAME = 'RoleName')
	ALTER TABLE WorkflowRoles
	ADD RoleName NVARCHAR(1000) NOT NULL CONSTRAINT DF_WorkflowRoles_RoleName DEFAULT (N'')
GO


