IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users'
		 AND COLUMN_NAME = 'TimeZoneInfo')
	ALTER TABLE Users
	ADD TimeZoneInfo NVARCHAR(256) NOT NULL CONSTRAINT DF_Users_TimeZoneInfo DEFAULT ('')

GO
