IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'StudyDictionaryRegistrations')
	DROP TABLE StudyDictionaryRegistrations

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'BitMaskLookup')
	DROP TABLE BitMaskLookup

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'AutoCodeStatusR')
	DROP TABLE AutoCodeStatusR

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CoderSegments')
	DROP TABLE CoderSegments

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CoderSegmentTypeR')
	DROP TABLE CoderSegmentTypeR

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CodingActionR')
	DROP TABLE CodingActionR

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CodingInclusionTypeR')
	DROP TABLE CodingInclusionTypeR

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionaryVersionLevelRecursion')
	DROP TABLE MedicalDictionaryVersionLevelRecursion

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictTermTypeR')
	DROP TABLE MedicalDictTermTypeR

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictVerStatusR')
	DROP TABLE MedicalDictVerStatusR

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'TherapeuticAreaR')
	DROP TABLE TherapeuticAreaR
