IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DoNotAutoCodeTerms'
		 AND COLUMN_NAME = 'ListId')
BEGIN
	ALTER TABLE DoNotAutoCodeTerms
	ADD ListId INT NOT NULL CONSTRAINT DF_DoNotAutoCodeTerms_ListId DEFAULT (0)
END
GO

IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'DoNotAutoCodeLists'))
BEGIN
		CREATE TABLE [dbo].[DoNotAutoCodeLists](
		ListId INT IDENTITY(1,1) NOT NULL,
		ListName NVARCHAR(200) NOT NULL CONSTRAINT DF_DoNotAutoCodeLists_ListName DEFAULT (''),
		MedicalDictionaryVersionLocaleKey VARCHAR(100) NOT NULL CONSTRAINT DF_DoNotAutoCodeLists_MedicalDictionaryVersionLocaleKey DEFAULT (''),
		SegmentId INT NOT NULL CONSTRAINT DF_DoNotAutoCodeLists_SegmentId DEFAULT (0),

		Created DATETIME NOT NULL CONSTRAINT DF_DoNotAutoCodeLists_Created DEFAULT (GETUTCDATE()), -- audit

	CONSTRAINT [PK_DoNotAutoCodeLists] PRIMARY KEY CLUSTERED 
	(
		ListId ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE UNIQUE NONCLUSTERED INDEX [UIX_DoNotAutoCodeLists_ListSegment] 
	ON [dbo].[DoNotAutoCodeLists] 
	(
		ListName ASC,
		SegmentId ASC
	)
	WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

END

