IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CoderLocaleAddlInfo')
	DROP TABLE CoderLocaleAddlInfo
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'HealthCheckStatistics')
	DROP TABLE HealthCheckStatistics
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'HealthCheckRuns')
	DROP TABLE HealthCheckRuns
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'HealthChecksR')
	DROP TABLE HealthChecksR
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_Codes')
	DROP TABLE ICD_Codes
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_Blocks')
	DROP TABLE ICD_Blocks
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_Chapters')
	DROP TABLE ICD_Chapters
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MorbL')
	DROP TABLE ICD_MorbL
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MortL1')
	DROP TABLE ICD_MortL1
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MortL1Bl')
	DROP TABLE ICD_MortL1Bl
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MortL2')
	DROP TABLE ICD_MortL2
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MortL3')
	DROP TABLE ICD_MortL3
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MortL3Bl')
	DROP TABLE ICD_MortL3Bl
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ICD_MortL4')
	DROP TABLE ICD_MortL4
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Interactions')
	DROP TABLE Interactions
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'InteractionStatusR')
	DROP TABLE InteractionStatusR
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ObjectSegmentStatusR')
	DROP TABLE ObjectSegmentStatusR
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ObjRefModelR')
	DROP TABLE ObjRefModelR
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'PermissionR')
	DROP TABLE PermissionR
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'RolePermissionR')
	DROP TABLE RolePermissionR
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'VariableDictAssignment')
	DROP TABLE VariableDictAssignment