IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'CodingElements'
		AND COLUMN_NAME = 'SourceLine')
BEGIN
	ALTER TABLE CodingElements
	ADD SourceLine NVARCHAR(256) CONSTRAINT DF_CodingElements_SourceLine DEFAULT (N'')
END

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'CodingElements'
		AND COLUMN_NAME = 'SourceSite')
BEGIN
	ALTER TABLE CodingElements
	ADD SourceSite NVARCHAR(256) CONSTRAINT DF_CodingElements_SourceSite DEFAULT (N'')
END

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'CodingElements'
		AND COLUMN_NAME = 'SourceEvent')
BEGIN
	ALTER TABLE CodingElements
	ADD SourceEvent NVARCHAR(256) CONSTRAINT DF_CodingElements_SourceEvent DEFAULT (N'')
END