IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ObjectSegments'
		 AND COLUMN_NAME = 'Deleted')
	ALTER TABLE ObjectSegments
	ADD Deleted BIT NOT NULL CONSTRAINT DF_ObjectSegments_Deleted DEFAULT ((0))
GO