// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Coder.RegressionTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("This feature file will verify the Task page\'s history tab section for a verbatim " +
        "term.")]
    [NUnit.Framework.CategoryAttribute("specTaskPageCodingHistoryTab.feature")]
    [NUnit.Framework.CategoryAttribute("CoderCore")]
    public partial class ThisFeatureFileWillVerifyTheTaskPageSHistoryTabSectionForAVerbatimTerm_Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "specTaskPageCodingHistoryTab.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "This feature file will verify the Task page\'s history tab section for a verbatim " +
                    "term.", "\r\n_ The following environment configuration settings were enabled:\r\n\r\n Empty Syno" +
                    "nym Lists Registered:\r\n Synonym List 1: MedDRA       (ENG) 11.0   Primary List\r\n" +
                    " Synonym List 2: WhoDrugDDEB2 (ENG) 200703 Primary List\r\n Synonym List 3: WhoDru" +
                    "gDDEC  (ENG) 200703 Primary List\r\n\r\n Common Configurations:\r\nConfiguration Name\t" +
                    "| Force Primary Path Selection (MedDRA) | Synonym Creation Policy Flag | Bypass " +
                    "Reconsider Upon Reclassify | Default Select Threshold | Default Suggest Threshol" +
                    "d | Auto Add Synonyms | Auto Approve | Term Requires Approval (IsApprovalRequire" +
                    "d )  | Term Auto Approve with synonym (IsAutoApproval)   |IsBypassTransmit\t\t|\r\nB" +
                    "asic\t\t\t| TRUE                                  | Always Active                | " +
                    "TRUE                              | 100                      | 70               " +
                    "         | TRUE              | FALSE        | TRUE                              " +
                    "            | TRUE                                              |TRUE\t\t\t\t|\r\nNo A" +
                    "pproval\t\t| TRUE                                  | Always Active                " +
                    "| TRUE                              | 100                      | 70             " +
                    "           | TRUE              | FALSE        | FALSE                           " +
                    "              | TRUE                                              |TRUE\t\t\t\t|\r\nRe" +
                    "consider\t\t| TRUE                                  | Always Active               " +
                    " | FALSE                             | 100                      | 70            " +
                    "            | TRUE              | FALSE        | TRUE                           " +
                    "               | TRUE                                              |TRUE\t\t\t\t|\r\nA" +
                    "pproval\t\t| TRUE                                  | Always Active                " +
                    "| FALSE                             | 100                      | 70             " +
                    "           | FALSE             | FALSE        | TRUE                            " +
                    "              | FALSE                                             |TRUE\t\t\t\t|\r\nCo" +
                    "mpleted Reconsider\t| TRUE                                  | Always Active      " +
                    "          | TRUE                              | 100                      | 70   " +
                    "                     | TRUE              | FALSE        | TRUE                  " +
                    "                        | TRUE                                              |FAL" +
                    "SE\t\t\t\t|", ProgrammingLanguage.CSharp, new string[] {
                        "specTaskPageCodingHistoryTab.feature",
                        "CoderCore"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a Waiting Approval task with informatio" +
            "n on User, Action, Status, Verbatim Term, Comment, and TimeStamp")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_001")]
        public virtual void TheFollowingWillShowCodingHistoryOfAWaitingApprovalTaskWithInformationOnUserActionStatusVerbatimTermCommentAndTimeStamp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a Waiting Approval task with informatio" +
                    "n on User, Action, Status, Verbatim Term, Comment, and TimeStamp", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_001"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 25
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Me" +
                    "dDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table1.AddRow(new string[] {
                        "Burn",
                        "LLT"});
#line 26
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table1, "When ");
#line 29
  testRunner.When("I view task \"BURN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment"});
            table2.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Approval",
                        "BURN",
                        "Auto coded by direct dictionary match"});
            table2.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "BURN",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=true,IsAuto" +
                            "Approval=false,IsBypassTransmit=True]"});
#line 30
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Term Path Coding history of a task with a coding decision" +
            " that is shown expanded")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_002")]
        public virtual void TheFollowingWillShowTermPathCodingHistoryOfATaskWithACodingDecisionThatIsShownExpanded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Term Path Coding history of a task with a coding decision" +
                    " that is shown expanded", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_002"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 40
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Me" +
                    "dDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table3.AddRow(new string[] {
                        "Burn",
                        "LLT"});
#line 41
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table3, "When ");
#line 44
  testRunner.When("I view task \"BURN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Level",
                        "Term Path",
                        "Code"});
            table4.AddRow(new string[] {
                        "SOC",
                        "Injury, poisoning and procedural complications: 10022117",
                        "10022117"});
            table4.AddRow(new string[] {
                        "HLGT",
                        "Injuries by physical agents: 10022119",
                        "10022119"});
            table4.AddRow(new string[] {
                        "HLT",
                        "Thermal burns: 10043418",
                        "10043418"});
            table4.AddRow(new string[] {
                        "PT",
                        "Thermal burn: 10053615",
                        "10053615"});
            table4.AddRow(new string[] {
                        "LLT",
                        "Burn: 10006634",
                        "10006634"});
#line 45
  testRunner.Then("I verify the following Coding history term full path information is displayed in " +
                    "row \"1\"", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Term Path Coding history of a task with a coding decision" +
            " that is contracted")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_003")]
        public virtual void TheFollowingWillShowTermPathCodingHistoryOfATaskWithACodingDecisionThatIsContracted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Term Path Coding history of a task with a coding decision" +
                    " that is contracted", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_003"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 58
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Me" +
                    "dDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table5.AddRow(new string[] {
                        "Burn",
                        "LLT"});
#line 59
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table5, "When ");
#line 62
  testRunner.When("I view task \"BURN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Level",
                        "Term Path",
                        "Code"});
            table6.AddRow(new string[] {
                        "LLT",
                        "Burn: 10006634",
                        "10006634"});
#line 63
  testRunner.Then("I verify the following Coding history selected term path information is displayed" +
                    " in row \"1\"", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of an Approved and Reconsidered task.")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_004")]
        public virtual void TheFollowingWillShowCodingHistoryOfAnApprovedAndReconsideredTask_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of an Approved and Reconsidered task.", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_004"});
#line 70
this.ScenarioSetup(scenarioInfo);
#line 72
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Me" +
                    "dDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table7.AddRow(new string[] {
                        "Burn",
                        "LLT"});
#line 73
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table7, "When ");
#line 76
  testRunner.When("approving task \"BURN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
  testRunner.And("reclassifying task \"BURN\" with a comment \"Test Automation Comment\" and Include Au" +
                    "tocoded Items set to \"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
  testRunner.And("I view task \"BURN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table8.AddRow(new string[] {
                        "<User>",
                        "Reclassify",
                        "Reconsider",
                        "BURN",
                        "Test Automation Comment",
                        "<TimeStamp>"});
            table8.AddRow(new string[] {
                        "<User>",
                        "Complete Without Transmission",
                        "Completed",
                        "BURN",
                        "Transmission Queue Number:",
                        "<TimeStamp>"});
            table8.AddRow(new string[] {
                        "<User>",
                        "Approve",
                        "Waiting Transmission",
                        "BURN",
                        "",
                        "<TimeStamp>"});
            table8.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Approval",
                        "BURN",
                        "Auto coded by direct dictionary match",
                        "<TimeStamp>"});
            table8.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "BURN",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=true,IsAuto" +
                            "Approval=false,IsBypassTransmit=True]",
                        "<TimeStamp>"});
#line 79
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of ReCoded task.")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_005")]
        public virtual void TheFollowingWillShowCodingHistoryOfReCodedTask_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of ReCoded task.", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_005"});
#line 90
this.ScenarioSetup(scenarioInfo);
#line 91
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Me" +
                    "dDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table9.AddRow(new string[] {
                        "Burn",
                        "LLT"});
#line 92
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table9, "When ");
#line 95
  testRunner.When("I recode task \"BURN\" with comment \"Recode comment.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 96
  testRunner.And("I view task \"BURN\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table10.AddRow(new string[] {
                        "<User>",
                        "ReCode",
                        "Waiting Manual Code",
                        "BURN",
                        "Recode comment.",
                        "<TimeStamp>"});
            table10.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Approval",
                        "BURN",
                        "Auto coded by direct dictionary match",
                        "<TimeStamp>"});
            table10.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "BURN",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=true,IsAuto" +
                            "Approval=false,IsBypassTransmit=True]",
                        "<TimeStamp>"});
#line 97
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that was completed without trans" +
            "mission, this applies to Manage External Verbatims")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_006")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatWasCompletedWithoutTransmissionThisAppliesToManageExternalVerbatims()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that was completed without trans" +
                    "mission, this applies to Manage External Verbatims", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_006"});
#line 107
this.ScenarioSetup(scenarioInfo);
#line 108
  testRunner.Given("a \"Reconsider\" Coder setup with no tasks and no synonyms and dictionary \"MedDRA E" +
                    "NG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table11.AddRow(new string[] {
                        "ANGIO-EDEMA",
                        "LLT"});
#line 109
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table11, "When ");
#line 112
  testRunner.When("reclassifying task \"ANGIO-EDEMA\" with a comment \"Test Automation Comment\" and Inc" +
                    "lude Autocoded Items set to \"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 113
  testRunner.And("I view task \"ANGIO-EDEMA\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table12.AddRow(new string[] {
                        "<User>",
                        "Reclassify",
                        "Reconsider",
                        "ANGIO-EDEMA",
                        "Test Automation Comment",
                        "<TimeStamp>"});
            table12.AddRow(new string[] {
                        "<SystemUser>",
                        "Complete Without Transmission",
                        "Completed",
                        "ANGIO-EDEMA",
                        "Transmission Queue Number:",
                        "<TimeStamp>"});
            table12.AddRow(new string[] {
                        "<SystemUser>",
                        "Auto Approve Internal",
                        "Waiting Transmission",
                        "ANGIO-EDEMA",
                        "Auto coded by direct dictionary match",
                        "<TimeStamp>"});
            table12.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Approval",
                        "ANGIO-EDEMA",
                        "Auto coded by direct dictionary match",
                        "<TimeStamp>"});
            table12.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "ANGIO-EDEMA",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=true,IsAuto" +
                            "Approval=true,IsBypassTransmit=True]",
                        "<TimeStamp>"});
#line 114
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that has been manually coded")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_007")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatHasBeenManuallyCoded()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that has been manually coded", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_007"});
#line 126
this.ScenarioSetup(scenarioInfo);
#line 127
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Wh" +
                    "oDrugDDEB2 ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table13.AddRow(new string[] {
                        "ASPORIZ3",
                        "PRODUCT"});
#line 128
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table13, "When ");
#line 131
  testRunner.When("task \"ASPORIZ3\" is coded to term \"ASPIRIN PLUS C\" at search level \"Preferred Name" +
                    "\" with code \"003467 01 001\" at level \"PN\" and a synonym is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 132
  testRunner.And("I view task \"ASPORIZ3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table14.AddRow(new string[] {
                        "<User>",
                        "Browse And Code",
                        "Waiting Approval",
                        "ASPORIZ3",
                        "",
                        "<TimeStamp>"});
            table14.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Manual Code",
                        "ASPORIZ3",
                        "",
                        "<TimeStamp>"});
            table14.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "ASPORIZ3",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=true,IsAuto" +
                            "Approval=false,IsBypassTransmit=True]",
                        "<TimeStamp>"});
#line 133
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that has been transmitted")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_008")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatHasBeenTransmitted()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that has been transmitted", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_008"});
#line 143
this.ScenarioSetup(scenarioInfo);
#line 144
  testRunner.Given("a \"Completed Reconsider\" Coder setup with no tasks and no synonyms and dictionary" +
                    " \"MedDRA ENG 11.0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table15.AddRow(new string[] {
                        "ANGIONEUROTIC OEDEMA AGGRAVATED",
                        "LLT"});
#line 145
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table15, "When ");
#line 148
  testRunner.When("reclassifying task \"ANGIONEUROTIC OEDEMA AGGRAVATED\" with a comment \"Test Automat" +
                    "ion Comment\" and Include Autocoded Items set to \"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 149
  testRunner.And("I view task \"ANGIONEUROTIC OEDEMA AGGRAVATED\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table16.AddRow(new string[] {
                        "<User>",
                        "Reclassify",
                        "Waiting Manual Code",
                        "ANGIONEUROTIC OEDEMA AGGRAVATED",
                        "Test Automation Comment",
                        "<TimeStamp>"});
            table16.AddRow(new string[] {
                        "<SystemUser>",
                        "Complete Without Transmission",
                        "Completed",
                        "ANGIONEUROTIC OEDEMA AGGRAVATED",
                        "Transmission Queue Number:",
                        "<TimeStamp>"});
            table16.AddRow(new string[] {
                        "<SystemUser>",
                        "Auto Approve Internal",
                        "Waiting Transmission",
                        "ANGIONEUROTIC OEDEMA AGGRAVATED",
                        "Auto coded by direct dictionary match",
                        "<TimeStamp>"});
            table16.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Approval",
                        "ANGIONEUROTIC OEDEMA AGGRAVATED",
                        "Auto coded by direct dictionary match",
                        "<TimeStamp>"});
            table16.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "ANGIONEUROTIC OEDEMA AGGRAVATED",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=true,IsAuto" +
                            "Approval=true,IsBypassTransmit=True]",
                        "<TimeStamp>"});
#line 150
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table16, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that has been Auto Approved and " +
            "reclassified with Bypass Reconsider Upon Reclassify turned on")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_009")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatHasBeenAutoApprovedAndReclassifiedWithBypassReconsiderUponReclassifyTurnedOn()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that has been Auto Approved and " +
                    "reclassified with Bypass Reconsider Upon Reclassify turned on", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_009"});
#line 161
this.ScenarioSetup(scenarioInfo);
#line 162
  testRunner.Given("a \"No Approval\" Coder setup with no tasks and no synonyms and dictionary \"WhoDrug" +
                    "DDEB2 ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table17.AddRow(new string[] {
                        "amethadone",
                        "PRODUCT"});
#line 163
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table17, "When ");
#line 166
  testRunner.When("task \"amethadone\" is coded to term \"methadone\" at search level \"Preferred Name\" w" +
                    "ith code \"000689 01 001\" at level \"PN\" and a synonym is created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 167
  testRunner.And("reclassifying task \"amethadone\" with a comment \"Test Automation Comment\" and Incl" +
                    "ude Autocoded Items set to \"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
  testRunner.And("I view task \"amethadone\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table18.AddRow(new string[] {
                        "<User>",
                        "Reclassify",
                        "Waiting Manual Code",
                        "AMETHADONE",
                        "Test Automation Comment",
                        "<TimeStamp>"});
            table18.AddRow(new string[] {
                        "<User>",
                        "Complete Without Transmission",
                        "Completed",
                        "AMETHADONE",
                        "Transmission Queue Number:",
                        "<TimeStamp>"});
            table18.AddRow(new string[] {
                        "<User>",
                        "Browse And Code",
                        "Waiting Transmission",
                        "AMETHADONE",
                        "",
                        "<TimeStamp>"});
            table18.AddRow(new string[] {
                        "<SystemUser>",
                        "Start Auto Code",
                        "Waiting Manual Code",
                        "AMETHADONE",
                        "",
                        "<TimeStamp>"});
            table18.AddRow(new string[] {
                        "<SystemUser>",
                        "",
                        "Start",
                        "AMETHADONE",
                        "Workflow=DEFAULT,WorkflowVariables[IsAutoCode=True,IsApprovalRequired=false,IsAut" +
                            "oApproval=true,IsBypassTransmit=True]",
                        "<TimeStamp>"});
#line 169
  testRunner.Then("I verify the following Coding History information is displayed", ((string)(null)), table18, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that has a status of waiting app" +
            "roval where an option of adding a comment is allowed")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_010")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatHasAStatusOfWaitingApprovalWhereAnOptionOfAddingACommentIsAllowed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that has a status of waiting app" +
                    "roval where an option of adding a comment is allowed", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_010"});
#line 181
this.ScenarioSetup(scenarioInfo);
#line 182
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Wh" +
                    "oDrugDDEB2 ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table19.AddRow(new string[] {
                        "ARMILLARISIN A",
                        "PRODUCT"});
#line 183
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table19, "When ");
#line 186
  testRunner.When("a user adds a comment \"Adding a comment!\" for task \"ARMILLARISIN A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table20.AddRow(new string[] {
                        "<User>",
                        "Add Comment",
                        "Waiting Approval",
                        "ARMILLARISIN A",
                        "Adding a comment!",
                        "<TimeStamp>"});
#line 187
  testRunner.Then("the Coding History contains following information", ((string)(null)), table20, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that has a status of waiting man" +
            "ual code where an option of adding a comment is allowed")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_011")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatHasAStatusOfWaitingManualCodeWhereAnOptionOfAddingACommentIsAllowed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that has a status of waiting man" +
                    "ual code where an option of adding a comment is allowed", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_011"});
#line 194
this.ScenarioSetup(scenarioInfo);
#line 195
  testRunner.Given("a \"Basic\" Coder setup with no tasks and no synonyms and dictionary \"WhoDrugDDEB2 " +
                    "ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table21.AddRow(new string[] {
                        "METH-",
                        "PRODUCT"});
#line 196
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table21, "When ");
#line 199
  testRunner.When("a user adds a comment \"Adding a comment!\" for task \"METH-\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table22.AddRow(new string[] {
                        "<User>",
                        "Add Comment",
                        "Waiting Manual Code",
                        "METH-",
                        "Adding a comment!",
                        "<TimeStamp>"});
#line 200
  testRunner.Then("the Coding History contains following information", ((string)(null)), table22, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The following will show Coding history of a term that has a status of reconsider " +
            "where an option of adding a comment is allowed")]
        [NUnit.Framework.CategoryAttribute("VAL")]
        [NUnit.Framework.CategoryAttribute("Release2015.3.0")]
        [NUnit.Framework.CategoryAttribute("PBMCC_163324_012")]
        public virtual void TheFollowingWillShowCodingHistoryOfATermThatHasAStatusOfReconsiderWhereAnOptionOfAddingACommentIsAllowed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The following will show Coding history of a term that has a status of reconsider " +
                    "where an option of adding a comment is allowed", new string[] {
                        "VAL",
                        "Release2015.3.0",
                        "PBMCC_163324_012"});
#line 207
this.ScenarioSetup(scenarioInfo);
#line 208
  testRunner.Given("a \"Waiting Approval\" Coder setup with no tasks and no synonyms and dictionary \"Wh" +
                    "oDrugDDEB2 ENG 200703\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Verbatim Term",
                        "Dictionary Level"});
            table23.AddRow(new string[] {
                        "ARMILLARISIN A",
                        "PRODUCT"});
#line 209
  testRunner.When("the following externally managed verbatim requests are made", ((string)(null)), table23, "When ");
#line 212
  testRunner.And("approve and reclassify task \"ARMILLARISIN A\" with Include Autocoded Items set to " +
                    "\"True\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 213
  testRunner.When("a user adds a comment \"Adding a comment!\" for task \"ARMILLARISIN A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "User",
                        "Action",
                        "Status",
                        "Verbatim Term",
                        "Comment",
                        "Time Stamp"});
            table24.AddRow(new string[] {
                        "<User>",
                        "Add Comment",
                        "Reconsider",
                        "ARMILLARISIN A",
                        "Adding a comment!",
                        "<TimeStamp>"});
#line 214
  testRunner.Then("the Coding History contains following information", ((string)(null)), table24, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
