 IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'UserPreferences'
		 AND COLUMN_NAME = 'DisplayPrimaryPathOnly')
	ALTER TABLE UserPreferences
	ADD DisplayPrimaryPathOnly BIT NOT NULL DEFAULT 0
GO  
