IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'RedFlags'))
BEGIN
	CREATE TABLE [dbo].[RedFlags](
		[RedFlagID] [int] IDENTITY(1,1) NOT NULL,
		[RedFlagDescription] NVARCHAR(MAX) NOT NULL,
		[IsClosed] [BIT] NOT NULL CONSTRAINT DF_RedFlags_IsClosed DEFAULT (0),
		SegmentID INT,
		StudyID INT,
		UserID INT,
		SourceSystemID INT,
		[Created] [datetime] NOT NULL CONSTRAINT DF_RedFlags_Created DEFAULT (GETUTCDATE()),
		[Updated] [datetime] NOT NULL CONSTRAINT DF_RedFlags_Updated DEFAULT (GETUTCDATE()),
	 CONSTRAINT [PK_RedFlags] PRIMARY KEY CLUSTERED 
	(
		[RedFlagID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO
 