--obosolete tables
--MedDictTermStatusR
--MedicalDictionaryTermRel
--MedicalDictionaryAlgorithm
--MedicalDictionaryUseAlgorithm


IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionary')
BEGIN
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_DoNotAutoCodeTerms_MedicalDictionary')) 
	BEGIN 
		ALTER TABLE DoNotAutoCodeTerms 
		DROP CONSTRAINT FK_DoNotAutoCodeTerms_MedicalDictionary
	END 
	
	DROP TABLE dbo.MedicalDictionary
END

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionaryLevelMapping')
	DROP TABLE dbo.MedicalDictionaryLevelMapping

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionaryTermRel')
	DROP Table  dbo.MedicalDictionaryTermRel
	
	IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictTermStatusR')
	DROP Table  dbo.MedDictTermStatusR
	
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionaryVersion')
BEGIN
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_Suggestion_DictionaryVersion')) 
	BEGIN 
		ALTER TABLE CodingSuggestions 
		DROP CONSTRAINT FK_Suggestion_DictionaryVersion
	END 
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_DoNotAutoCodeTerms_MedicalDictionaryVersion')) 
	BEGIN 
		ALTER TABLE DoNotAutoCodeTerms 
		DROP CONSTRAINT FK_DoNotAutoCodeTerms_MedicalDictionaryVersion
	END 
	
	DROP TABLE dbo.MedicalDictionaryVersion
END

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictVerLocaleStatus')
	DROP Table  dbo.MedicalDictVerLocaleStatus
	
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictLevelComponents')
BEGIN
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_MedDictLevelCmpntUpdates_Fn_MedicalDictLevelComponents')) 
	BEGIN 
		ALTER TABLE MedDictLevelCmpntUpdates 
		DROP CONSTRAINT FK_MedDictLevelCmpntUpdates_Fn_MedicalDictLevelComponents
	END 
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_MedDictLevelCmpntUpdates_In_MedicalDictLevelComponents')) 
	BEGIN 
		ALTER TABLE MedDictLevelCmpntUpdates 
		DROP CONSTRAINT FK_MedDictLevelCmpntUpdates_In_MedicalDictLevelComponents
	END 
	
	DROP TABLE dbo.MedicalDictLevelComponents
END

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictTermComponents')
	DROP Table  dbo.MedicalDictTermComponents
	
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictComponentTypes')
BEGIN
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_MedDictVerLvlComponents_MedicalDictComponentTypes')) 
	BEGIN 
		ALTER TABLE MedDictVerLvlComponents 
		DROP CONSTRAINT FK_MedDictVerLvlComponents_MedicalDictComponentTypes
	END 
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_VariableAssignment_Types')) 
	BEGIN 
		ALTER TABLE VariableDictAssignment 
		DROP CONSTRAINT FK_VariableAssignment_Types
	END 
	
	DROP TABLE dbo.MedicalDictComponentTypes
END

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionaryLevel')
BEGIN
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_CodingElements_DictionaryLevel')) 
	BEGIN 
		ALTER TABLE CodingElements 
		DROP CONSTRAINT FK_CodingElements_DictionaryLevel
	END
	
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_DoNotAutoCodeTerms_MedicalDictionaryLevel')) 
	BEGIN 
		ALTER TABLE DoNotAutoCodeTerms 
		DROP CONSTRAINT FK_DoNotAutoCodeTerms_MedicalDictionaryLevel
	END  
	
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_MedDictSynonymWasteBasket_MedicalDictionaryLevel')) 
	BEGIN 
		ALTER TABLE MedDictSynonymWasteBasket 
		DROP CONSTRAINT FK_MedDictSynonymWasteBasket_MedicalDictionaryLevel
	END 
	
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_MedicalDictionaryTemplateLevels_DictionaryLevelId')) 
	BEGIN 
		ALTER TABLE MedicalDictionaryTemplateLevel 
		DROP CONSTRAINT FK_MedicalDictionaryTemplateLevels_DictionaryLevelId
	END   
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_MedicalDictionaryVersionLevelRecursion_DictionaryLevelID')) 
	BEGIN 
		ALTER TABLE MedicalDictionaryVersionLevelRecursion 
		DROP CONSTRAINT FK_MedicalDictionaryVersionLevelRecursion_DictionaryLevelID
	END   
	DROP TABLE dbo.MedicalDictionaryLevel
END

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictionaryTerm')
BEGIN
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_Suggestions_DictionaryTerm')) 
	BEGIN 
		ALTER TABLE CodingSuggestions 
		DROP CONSTRAINT FK_Suggestions_DictionaryTerm
	END 
	IF EXISTS (SELECT NULL FROM sys.foreign_keys 
	WHERE object_id = OBJECT_ID(N'FK_DoNotAutoCodeTerms_MedicalDictionaryTerm')) 
	BEGIN 
		ALTER TABLE DoNotAutoCodeTerms 
		DROP CONSTRAINT FK_DoNotAutoCodeTerms_MedicalDictionaryTerm
	END 
	DROP TABLE dbo.MedicalDictionaryTerm
END
---Drop staging tables for dictionary loading and versioning
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'JDRUG')
BEGIN
	DROP TABLE dbo.JDRUG
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'JDRUG_J')
BEGIN
	DROP TABLE dbo.JDRUG_J
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_hlgt')
BEGIN
	DROP TABLE dbo.Meddra_hlgt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_hlgt_hlt')
BEGIN
	DROP TABLE dbo.Meddra_hlgt_hlt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_hlt')
BEGIN
	DROP TABLE dbo.Meddra_hlt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_hlt_pt')
BEGIN
	DROP TABLE dbo.Meddra_hlt_pt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_intl_ord')
BEGIN
	DROP TABLE dbo.Meddra_intl_ord
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_llt')
BEGIN
	DROP TABLE dbo.Meddra_llt
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_mdhier')
BEGIN
	DROP TABLE dbo.Meddra_mdhier
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_pt')
BEGIN
	DROP TABLE dbo.Meddra_pt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_soc')
BEGIN
	DROP TABLE dbo.Meddra_soc
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_soc_hlgt')
BEGIN
	DROP TABLE dbo.Meddra_soc_hlgt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_spec_pt')
BEGIN
	DROP TABLE dbo.Meddra_spec_pt
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'Meddra_spec')
BEGIN
	DROP TABLE dbo.Meddra_spec
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CCODE_B')
BEGIN
	DROP TABLE dbo.CCODE_B
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'DDSOURCE_B')
BEGIN
	DROP TABLE dbo.DDSOURCE_B
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MAN_B')
BEGIN
	DROP TABLE dbo.MAN_B
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'INA_B')
BEGIN
	DROP TABLE dbo.INA_B
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'BNA_B')
BEGIN
	DROP TABLE dbo.BNA_B
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'DD_B')
BEGIN
	DROP TABLE dbo.DD_B
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'DDA_B')
BEGIN
	DROP TABLE dbo.DDA_B
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ING_B')
BEGIN
	DROP TABLE dbo.ING_B
END 	

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CCODE')
BEGIN
	DROP TABLE dbo.CCODE
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ATC')
BEGIN
	DROP TABLE dbo.ATC
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ORG')
BEGIN
	DROP TABLE dbo.ORG
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'PF')
BEGIN
	DROP TABLE dbo.PF
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'PRG')
BEGIN
	DROP TABLE dbo.PRG
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'PRT')
BEGIN
	DROP TABLE dbo.PRT
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'SRCE')
BEGIN
	DROP TABLE dbo.SRCE
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'STR')
BEGIN
	DROP TABLE dbo.STR
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'SUN')
BEGIN
	DROP TABLE dbo.SUN
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'UNIT')
BEGIN
	DROP TABLE dbo.UNIT
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MP')
BEGIN
	DROP TABLE dbo.MP
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'PP')
BEGIN
	DROP TABLE dbo.PP
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'THG')
BEGIN
	DROP TABLE dbo.THG
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ING')
BEGIN
	DROP TABLE dbo.ING
END 
--end of dictionary staging tables
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictComponentUpdates')
BEGIN
	DROP TABLE dbo.MedDictComponentUpdates
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictLevelCmpntUpdates')
BEGIN
	DROP TABLE dbo.MedDictLevelCmpntUpdates
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictTermUpdates')
BEGIN
	DROP TABLE dbo.MedDictTermUpdates
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictVerChangeTypeR')
BEGIN
	DROP TABLE dbo.MedDictVerChangeTypeR
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictVerLvlComponents')
BEGIN
	DROP TABLE dbo.MedDictVerLvlComponents
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictVerTermComponents')
BEGIN
	DROP TABLE dbo.MedDictVerTermComponents
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictVerTerm')
BEGIN
	DROP TABLE dbo.MedicalDictVerTerm
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedicalDictVerTermRel')
BEGIN
	DROP TABLE dbo.MedicalDictVerTermRel
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MedDictVerChangeTypeR')
BEGIN
	DROP TABLE dbo.MedDictVerChangeTypeR
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ImpactAnalysisVersionDifference')
BEGIN
	DROP TABLE dbo.ImpactAnalysisVersionDifference
END

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'DictionarySpecificLogic')
BEGIN
	DROP TABLE dbo.DictionarySpecificLogic
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ComponentEngStrings')
BEGIN
	DROP TABLE dbo.ComponentEngStrings
END 

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ComponentJpnStrings')
BEGIN
	DROP TABLE dbo.ComponentJpnStrings
END 
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'ComponentLocStrings')
BEGIN
	DROP TABLE dbo.ComponentLocStrings
END 

--shrink database log file
EXECUTE spShrinkDB 1

 
