IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'AsyncTaskNodes')
BEGIN

	CREATE TABLE [dbo].[AsyncTaskNodes](
		AsyncTaskNodeID INT IDENTITY(1,1) NOT NULL, 
		Created DATETIME NOT NULL CONSTRAINT [DF_AsyncTaskNodes_Created] DEFAULT (GETUTCDATE()),
		Updated DATETIME NOT NULL CONSTRAINT [DF_AsyncTaskNodes_Updated] DEFAULT (GETUTCDATE()),
	 CONSTRAINT [PK_AsyncTaskNodes] PRIMARY KEY CLUSTERED 
	(
		[AsyncTaskNodeID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END
 

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'LongAsyncTasks')
BEGIN

	CREATE TABLE [dbo].[LongAsyncTasks](
		TaskId INT IDENTITY(1,1) NOT NULL,
		ReferenceId BIGINT NOT NULL, 
		IsComplete BIT NOT NULL CONSTRAINT DF_LongAsyncTasks_IsComplete DEFAULT (0), 
		IsFailed BIT NOT NULL CONSTRAINT DF_LongAsyncTasks_IsFailed DEFAULT (0),
		SegmentId INT NOT NULL, 
		LongAsyncTaskType TINYINT NOT NULL, 
		CommandType TINYINT NOT NULL,
		OngoingTaskHistoryId BIGINT NOT NULL CONSTRAINT DF_LongAsyncTasks_OngoingTaskHistoryId DEFAULT(-1),
	
		CacheVersion BIGINT NOT NULL CONSTRAINT DF_LongAsyncTasks_CacheVersion DEFAULT (0),
		
		EarliestAllowedStartTime DATETIME,

		Created DATETIME NOT NULL CONSTRAINT DF_LongAsyncTasks_Created DEFAULT (GETUTCDATE()),
		Updated DATETIME NOT NULL CONSTRAINT DF_LongAsyncTasks_Updated DEFAULT (GETUTCDATE()),
	 CONSTRAINT [PK_LongAsyncTasks] PRIMARY KEY CLUSTERED 
	(
		[TaskId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'LongAsyncTaskHistory')
BEGIN

	CREATE TABLE [dbo].[LongAsyncTaskHistory](
		TaskHistoryId INT IDENTITY(1,1) NOT NULL,
		TaskId INT NOT NULL, 
		IsFailed BIT NOT NULL CONSTRAINT DF_LongAsyncTaskHistory_IsFailed DEFAULT (0),
		TaskLog NVARCHAR(1000), 
		SegmentId INT NOT NULL, 
		CommandType TINYINT NOT NULL,
		AsyncTaskNodeId INT NOT NULL CONSTRAINT DF_LongAsyncTaskHistory_AsyncTaskNodeId DEFAULT (0), 

		Created DATETIME NOT NULL CONSTRAINT DF_LongAsyncTaskHistory_Created DEFAULT (GETUTCDATE()),
		Updated DATETIME NOT NULL CONSTRAINT DF_LongAsyncTaskHistory_Updated DEFAULT (GETUTCDATE()),
	 CONSTRAINT [PK_LongAsyncTaskHistory] PRIMARY KEY CLUSTERED 
	(
		[TaskHistoryId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END


IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'AsyncTaskNodeReports')
BEGIN

	CREATE TABLE [dbo].[AsyncTaskNodeReports](
		AsyncTaskNodeReportId INT IDENTITY(1,1) NOT NULL,
		AsyncTaskNodeId BIGINT NOT NULL, 
		ProcessCount INT NOT NULL, 
		ZombieTaskIds VARCHAR(1000), 

		Created DATETIME NOT NULL CONSTRAINT DF_AsyncTaskNodeReports_Created DEFAULT (GETUTCDATE()),
	 CONSTRAINT [PK_AsyncTaskNodeReports] PRIMARY KEY CLUSTERED 
	(
		[AsyncTaskNodeReportId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END


IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'StudyMigrationTraces')
BEGIN

	CREATE TABLE [dbo].[StudyMigrationTraces](
		StudyMigrationTraceId INT IDENTITY(1,1) NOT NULL,
		
        UserId INT NOT NULL, 
        SegmentId INT NOT NULL, 
        StudyId INT NOT NULL, 
        FromVersionId INT NOT NULL, 
        FromSynonymMgmtId INT NOT NULL, 
        ToVersionId INT NOT NULL, 
        ToSynonymMgmtId INT NOT NULL, 
        StudyDictionaryVersionId INT NOT NULL, 

		Created DATETIME NOT NULL CONSTRAINT DF_StudyMigrationTraces_Created DEFAULT (GETUTCDATE()),
		Updated DATETIME NOT NULL CONSTRAINT DF_StudyMigrationTraces_Updated DEFAULT (GETUTCDATE()),
	 CONSTRAINT [PK_StudyMigrationTraces] PRIMARY KEY CLUSTERED 
	(
		[StudyMigrationTraceId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

END