IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CodingQueries'))
BEGIN
		CREATE TABLE [dbo].[CodingQueries](
		QueryId INT IDENTITY(1,1) NOT NULL,
		CodingElementId INT NOT NULL CONSTRAINT DF_CodingQueries_CodingElementId DEFAULT (0),
		VerbatimTerm NVARCHAR(500) NOT NULL CONSTRAINT DF_CodingQueries_VerbatimTerm DEFAULT (N''),
		QueryUUID NVARCHAR(50) NOT NULL CONSTRAINT DF_CodingQueries_QueryUUID DEFAULT (N''),
		QueryRepeatKey INT NOT NULL CONSTRAINT DF_CodingQueries_QueryRepeatKey DEFAULT (0),
		Recipient NVARCHAR (450),
		QueryStatus TINYINT NOT NULL CONSTRAINT DF_CodingQueries_QueryStatus DEFAULT (0),
		QueryText NVARCHAR(4000),
		QueryResponse NVARCHAR(4000), 
		QueryNote NVARCHAR(4000), 
		UserRef NVARCHAR(100) NOT NULL CONSTRAINT DF_CodingQueries_UserRef DEFAULT (N''),
		DateTimeStamp DATETIME NOT NULL CONSTRAINT DF_CodingQueries_DateTimeStamp DEFAULT (GETUTCDATE()),
		Created DATETIME NOT NULL CONSTRAINT DF_CodingQueries_Created DEFAULT (GETUTCDATE())
	CONSTRAINT [PK_CodingQueries] PRIMARY KEY CLUSTERED 
	(
		[QueryId] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END