-- remove unreferenced tables
IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'AckNackTransmissions')
	DROP TABLE AckNackTransmissions

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'meddra_soc_j')
	DROP TABLE meddra_soc_j

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'meddra_pt_j')
	DROP TABLE meddra_pt_j

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'meddra_llt_j')
	DROP TABLE meddra_llt_j

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'meddra_hlt_j')
	DROP TABLE meddra_hlt_j

IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'meddra_hlgt_j')
	DROP TABLE meddra_hlgt_j


IF EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_NAME = 'meddictsynonymwastebasket')
	DROP TABLE meddictsynonymwastebasket

