-- ADD COLUMNS

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'StudyMigrationBackup'
			AND COLUMN_NAME = 'OldQueryStatus')
	ALTER TABLE StudyMigrationBackup
	ADD OldQueryStatus TINYINT NOT NULL DEFAULT (0)

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'StudyMigrationBackup'
			AND COLUMN_NAME = 'NewQueryStatus')
	ALTER TABLE StudyMigrationBackup
	ADD NewQueryStatus TINYINT NOT NULL DEFAULT (0)

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'StudyMigrationBackup'
			AND COLUMN_NAME = 'NewQueryHistoryId')
	ALTER TABLE StudyMigrationBackup
	ADD NewQueryHistoryId BIGINT NOT NULL DEFAULT (-1)

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'StudyMigrationBackup'
			AND COLUMN_NAME = 'NewQueryTransmissionQueueItemId')
	ALTER TABLE StudyMigrationBackup
	ADD NewQueryTransmissionQueueItemId BIGINT NOT NULL DEFAULT (-1)

IF NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'StudyMigrationBackup'
			AND COLUMN_NAME = 'NewQueryWorkflowHistoryId')
	ALTER TABLE StudyMigrationBackup
	ADD NewQueryWorkflowHistoryId BIGINT NOT NULL DEFAULT (-1)
