IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'InvalidTaskQueue'))
BEGIN
		CREATE TABLE [dbo].[InvalidTaskQueue](
		InvalidTaskQueueId INT IDENTITY(1,1) NOT NULL,
		
		TaskId INT NOT NULL,
		Succeeded BIT NOT NULL CONSTRAINT DF_InvalidTaskQueue_Succeeded DEFAULT (0),

		Created DATETIME NOT NULL CONSTRAINT DF_InvalidTaskQueue_Created DEFAULT (GETUTCDATE()),
		Updated DATETIME NOT NULL CONSTRAINT DF_InvalidTaskQueue_Updated DEFAULT (GETUTCDATE()),
	CONSTRAINT [PK_InvalidTaskQueue] PRIMARY KEY CLUSTERED 
	(
		InvalidTaskQueueId ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END