IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'MOTDAudits'))
BEGIN
		CREATE TABLE [dbo].[MOTDAudits](
		MOTDAuditId INT IDENTITY(1,1) NOT NULL,
		
		UserID INT NOT NULL CONSTRAINT DF_MOTDAudits_UserID DEFAULT (0),
		MOTDMessage NVARCHAR(1000) NOT NULL CONSTRAINT DF_MOTDAudits_MOTDMessage DEFAULT (N''),
		Locale CHAR(3) NOT NULL CONSTRAINT DF_MOTDAudits_QueryUUID DEFAULT ('eng'),

		Created DATETIME NOT NULL CONSTRAINT DF_MOTDAudits_Created DEFAULT (GETUTCDATE()),
		Updated DATETIME NOT NULL CONSTRAINT DF_MOTDAudits_Updated DEFAULT (GETUTCDATE()),
	CONSTRAINT [PK_MOTDAudits] PRIMARY KEY CLUSTERED 
	(
		MOTDAuditId ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END