
IF NOT EXISTS (SELECT NULL FROM sys.indexes
	WHERE name = 'IX_CodingElements_UUID')
BEGIN
	CREATE NONCLUSTERED INDEX [IX_CodingElements_UUID] ON [dbo].[CodingElements] 
	(
		[UUID] ASC
	)
	INCLUDE ( [SourceSystemId] ) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END
GO