IF NOT EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TrackableObjects'
		 AND COLUMN_NAME = 'AuditStudyGroupUUID')
	ALTER TABLE TrackableObjects
	ADD AuditStudyGroupUUID NVARCHAR(100) NOT NULL CONSTRAINT DF_TrackableObjects_AuditStudyGroupUUID DEFAULT (N'')
GO 

