IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CsvCodingJobErrorToken'))
BEGIN
		CREATE TABLE [dbo].[CsvCodingJobErrorToken](
		CsvErrorTokenId BIGINT IDENTITY(1,1) NOT NULL,
		CodingJobErrorId INT NOT NULL CONSTRAINT DF_CsvCodingJobErrorToken_CodingJobErrorId DEFAULT (0),
		TokenString VARCHAR(MAX) NOT NULL CONSTRAINT DF_CsvCodingJobErrorToken_TokenString DEFAULT (''),

	CONSTRAINT [PK_CsvCodingJobErrorToken] PRIMARY KEY CLUSTERED 
	(
		CsvErrorTokenId ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END


IF EXISTS 
	(SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CodingJobErrors'
		 AND COLUMN_NAME = 'UserFriendlyError')
BEGIN
	ALTER TABLE CodingJobErrors
	DROP CONSTRAINT DF_CodingJobErrors_UserFriendlyError

	ALTER TABLE CodingJobErrors
	DROP COLUMN UserFriendlyError
END
GO