IF (NOT EXISTS (SELECT NULL FROM INFORMATION_SCHEMA.TABLES
	WHERE TABLE_NAME = 'CodingJobErrors'))
BEGIN
		CREATE TABLE [dbo].[CodingJobErrors](
		CodingJobErrorId BIGINT IDENTITY(1,1) NOT NULL,
		
		CodingRequestId INT NOT NULL CONSTRAINT DF_CodingJobErrors_CodingRequestId DEFAULT (0),
		JobString NVARCHAR(MAX) NOT NULL CONSTRAINT DF_CodingJobErrors_JobString DEFAULT (N''),
		ErrorString NVARCHAR(MAX) NOT NULL CONSTRAINT DF_CodingJobErrors_ErrorString DEFAULT (N''),

		Created DATETIME NOT NULL CONSTRAINT DF_CodingJobErrors_Created DEFAULT (GETUTCDATE()),
	CONSTRAINT [PK_CodingJobErrors] PRIMARY KEY CLUSTERED 
	(
		CodingJobErrorId ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

